alertmanager:
  config:
    global:
      smtp_smarthost: "smtp.office365.com:587"
      smtp_from: "YOUR_EMAIL@yourcompany.com"
      smtp_auth_username: "YOUR_EMAIL@yourcompany.com"
      smtp_auth_password: "YOUR_PASSWORD_OR_APP_PASSWORD"
      smtp_require_tls: true

    route:
      receiver: "email-notifications"
      group_by: ["alertname", "deployment", "namespace"]
      group_wait: 10s
      group_interval: 30s
      repeat_interval: 30m

    receivers:
      - name: "email-notifications"
        email_configs:
          - to: "RECEIVER_EMAIL@yourcompany.com"
            send_resolved: true